name: cinema_go
description: "A Flutter project for a cinema booking application."
publish_to: 'none' # Set to 'none' for private packages

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # For iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Recommended lint rules for better coding practices

flutter:
  uses-material-design: true # Enables Material Design icons

  # Uncomment to add assets
  # assets:
  #   - images/example_image.jpeg

  # Uncomment to add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
